Updated dependancies. A few improvements as a side-effect:
Devolutions/prux pull request #14
Opened 2022-05-10 16:34 UTC by Samuel-B-D

- https support
- faster cache
- applied newer clippy

Note: only the dependancy `priority-queue = "1.2.1"` was added; other diff are just that I alphabetically ordered them with `cargo sort`.

2022-05-10 22:47 UTC, LucFauvel requested changes

2022-05-10 22:47 UTC, LucFauvel commented on src/proxy/utils.rs
> +                    //     s.splitn(2, '=').nth(1).and_then(|s| {
commented code?

2022-05-11 14:34 UTC, Samuel-B-D commented on src/proxy/utils.rs
> +                    //     s.splitn(2, '=').nth(1).and_then(|s| {
whoops, I'll clean that up

2022-05-11 19:51 UTC, LucFauvel approved these changes

2022-05-11 19:51 UTC, merged